#!/bin/sh
for FILE in $( git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp|m|mm)$' ) ; do
    if [[ -f "$FILE" ]]; then
        clang-format -i -style=file "${FILE}"
        git add "${FILE}"    
    fi
done